### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by brunoeducsantos** [MOLAorg/mola#26]
Hi,
Thanks for the amazing work.
It happens that all the links to the documentation are dead. Could you check it please?
Thanks,
Bruno

**Comment by jlblancoc** [comment]
Oh, thanks for reporting!

I think it was an issue with the dns. It should be fixed, within a few hours when dns propagates. If not, come back to report.

**Comment by brunoeducsantos** [comment]
Thanks a lot!
