### ISSUE TITLE
About 3D LiDAR SLAM from KITTI dataset

### ISSUE THREAD

**Issue by dibet** [MOLAorg/mola#34]
Hi, 
It is not an issue but I would like understand more about the code inside Mola, which is fantastic.
In this sample 3D LiDAR SLAM from KITTI dataset.
I would like to know if you are using landmarks in this sample for closure loop?
Best regards
Dibet

**Comment by jlblancoc** [comment]
Hi, thanks. 
Loop closure is solved using raw point clouds and simultaneously detected plane patches, via the mp2p_icp library.

**Comment by dibet** [comment]
then you use the planes as landmarks?

**Comment by jlblancoc** [comment]
I would say "no": there is not a **MAP** with landmarks. Planes are only used at present during keyframe-wise ICP alignment, but the "map" is just a pose graph as in most pose graph-based SLAM methods.

**Comment by dibet** [comment]
thanks by your comments
