### ISSUE TITLE
Accurate mapping in localization mode

### ISSUE THREAD

**Issue by MigVega** [MOLAorg/mola#48]
Dears,
I did not find a localization mode in the documentation, but assuming there is one, is it possible to use it (with a reference map) and do online mapping (with loop closure and optimization) at the same time? 
I believe this would be the solution for long-term localization and mapping, since you may already have a reliable map. However, not always the whole multisession data.
Thanks in advance.

**Comment by jlblancoc** [comment]
This would be feasible in theory, but complex in practice. It's not implemented at present in this framework. 

There's a localization only mode, thought.
