### ISSUE TITLE
DataSet Questions

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [MOLAorg/mola#51]
I installed MOLa on my ubuntu . I am used ROS2 humble but, how to implement kitti dataset or other dataset your system . I dont understand actually . 

Thank You .

**Comment by jlblancoc** [comment]
Right now, there is a lack of proper docs to easily jump in, sorry! 
In the meanwhile, you can always check the sources, and/or the ROS2 launch files in the [mola_demos](https://github.com/MOLAorg/mola/tree/develop/mola_demos/ros2-launchs) package.

For example, once [installed](https://docs.mola-slam.org/latest/installing.html) (for now, prefer build from sources for getting faster bug fixes) you can replay the KITTI dataset with: 

    ros2 launch mola_demos kitti-play.launch.py

and it shows something like: 

![Screenshot from 2024-04-04 01-39-08](https://github.com/MOLAorg/mola/assets/5497818/4bd9f57d-aafb-4316-a0f7-0cc6308a67de)


with both, MOLA GUI, and RViz showing the KITTI dataset, controls to pause, fast-forward it, etc. All sensor data is published to ROS2 topics, of course, for usage in any user application. 

For that to work, of course, you should first download the KITTI (or Mulran, KITTI-360, etc.) datasets, extracts it, and set the path to it in an environment variable (the launch will ask for it the first time).

**Comment by ahmet-f-gumustas** [comment]
Thank You for your response I try and return

**Comment by jlblancoc** [comment]
New tutorials are now available online: 
https://docs.mola-slam.org/latest/
