### ISSUE TITLE
Mola Demo

### ISSUE THREAD

**Issue by woreom** [MOLAorg/mola#54]
Hi,

Thank you for the great repo! I'm new to ROS and MOLA, so this might be a basic question. I can't run any of the demos, and the documentation seems to be from different versions, which is confusing. Could you provide a beginner-friendly demo and tutorial for using your work?

**Comment by jlblancoc** [comment]
Hi @woreom ! 
Same answer than https://github.com/MOLAorg/mola/issues/53#issuecomment-2189059469
This project is just to see a major new release and things are moving fast. The docs online are updated everyday and the missing mola_lidar_odometry package will be released asap, together with a paper explaining its details...

**Comment by woreom** [comment]
> Hi @woreom ! Same answer than [#53 (comment)](https://github.com/MOLAorg/mola/issues/53#issuecomment-2189059469) This project is just to see a major new release and things are moving fast. The docs online are updated everyday and the missing mola_lidar_odometry package will be released asap, together with a paper explaining its details...

Thanks 🙏🙏

**Comment by jlblancoc** [comment]
Now, step-by-step tutorials are available online: 
https://docs.mola-slam.org/latest/
