### ISSUE TITLE
can not  git clone 

### ISSUE THREAD

**Issue by sam1992xjh** [MOLAorg/mola#7]
Hi ,when I try
`
git clone --recurse-submodules https://github.com/MOLAorg/mola.git`
I was refuse to clone something.
for example:
'git@github.com:jlblancoc/mola-fe-g2o-dataset.git'
'git@github.com:jlblancoc/mola-fe-imu-preintegration.git'
'git@github.com:jlblancoc/mola-fe-lidar-3d.git'
...
it shows:
 Permission denied (publickey)

Is there any wrong?

**Comment by jlblancoc** [comment]
> I was refuse to clone something.

Sure... the project is still not officially released to the public ;-)
I'm working hard to document all modules and making some final code refactoring tasks, will be releasing modules as they are finished during this and the next week.

Cheers

**Comment by sam1992xjh** [comment]
Thank you～
